using System.Text;
using Azure.Search.Documents.Indexes;
using Its.Search.PrivateEye.Core.ParameterDefinitions;
using Microsoft.CodeAnalysis;

namespace Its.Search.PrivateEye.SourceGenerators;

[Generator]
public class SearchParameterGenerator : PrivateEyeGeneratorBase
{
    protected override void GenerateComponent(StringBuilder builder, ITypeSymbol indexDocumentType)
    {
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("using System;");
        builder.AppendLine("using Its.Search.PrivateEye.Core.ParameterDefinitions;");

        builder.AppendLine();
        if (GetComponentNamespace(indexDocumentType) is { } ns)
            builder.Append($"namespace {ns};");

        builder.AppendLine();

        builder.Append("public record ");
        var parametersRecordTypeName = indexDocumentType.Name + "SearchParameters";

        builder.Append(parametersRecordTypeName);
        builder.AppendLine("() {");
        GenerateProperties(builder, indexDocumentType);
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private void GenerateProperties(StringBuilder builder, ITypeSymbol symbol)
    {
        bool containsSearchableProperties = false;
        var propertyBuilder = symbol
            .GetMembers()
            .Where(it => it.Kind == SymbolKind.Property)
            .Cast<IPropertySymbol>()
            .SelectMany(ExtractTargetProperties)
            .Aggregate(new StringBuilder(), (propBuilder, propInfo) =>
            {
                var (_, property, isSearchable) = propInfo!.Value;
                containsSearchableProperties |= isSearchable;
                var paramTypeName = isSearchable
                    ? nameof(SearchableFieldParameters)
                    : "SimpleFieldParameters<" + property.Type.Name + ">";
                GenerateParameterProperty(propBuilder, property!.Name, paramTypeName);
                return propBuilder;
            });

        if (containsSearchableProperties)
        {
            GenerateParameterProperty(propertyBuilder, "FullText", nameof(FullTextSearchParameters));
        }

        builder.Append(propertyBuilder);
    }

    private static IEnumerable<(AttributeData, IPropertySymbol, bool)?> ExtractTargetProperties(IPropertySymbol property)
    {
        return property
            .GetAttributes()
            .Select<AttributeData, (AttributeData, IPropertySymbol, bool)?>(attribute =>
                attribute.AttributeClass?.Name switch
                {
                    nameof(SimpleFieldAttribute) => (attribute, property, false),
                    nameof(SearchableFieldAttribute) => (attribute, property, true),
                    _ => null
                }
            )
            .Where(it => it is not null);
    }

    private static void GenerateParameterProperty(StringBuilder propBuilder, string propertyName, string paramTypeName)
    {
        propBuilder.Append("    public ");
        propBuilder.Append(paramTypeName);
        propBuilder.Append(' ');
        propBuilder.Append(propertyName);
        propBuilder.AppendLine(" { get; init; } = new();");
    }

    protected override string GetComponentName() => "SearchParameters";

}
