using System.Text;
using Azure.Search.Documents.Indexes;
using Irrelephant.Search.PrivateEye.Core.Search;
using Microsoft.CodeAnalysis;

namespace Irrelephant.Search.PrivateEye.SourceGenerators;

[Generator]
public class SearchParameterGenerator : PrivateEyeGeneratorBase
{
    protected override void GenerateComponent(StringBuilder builder, ITypeSymbol indexDocumentType)
    {
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("using System;");
        builder.AppendLine("using Irrelephant.Search.PrivateEye.Core.Search;");

        builder.AppendLine();
        if (GetComponentNamespace(indexDocumentType) is { } ns)
            builder.Append($"namespace {ns};");

        builder.AppendLine();

        builder.Append("public record ");
        var parametersRecordTypeName = indexDocumentType.Name + "SearchParameters";
        builder.Append(parametersRecordTypeName);
        builder.AppendLine("() {");
        GenerateProperties(builder, indexDocumentType);
        builder.AppendLine("}");
        builder.AppendLine();
    }

    private void GenerateProperties(StringBuilder builder, ITypeSymbol symbol)
    {
        var propertyBuilder = symbol
            .GetMembers()
            .Where(it => it.Kind == SymbolKind.Property)
            .Cast<IPropertySymbol>()
            .SelectMany(ExtractTargetProperties)
            .Aggregate(new StringBuilder(), (propBuilder, propInfo) =>
            {
                var (_, property) = propInfo!.Value;
                var paramTypeName = "SearchField<" + property.Type.Name + ">";
                GenerateParameterProperty(propBuilder, property.Name, paramTypeName);
                return propBuilder;
            });

        GenerateParameterProperty(propertyBuilder, "FullText", nameof(FullTextSearchParameters));

        builder.Append(propertyBuilder);
    }

    private static IEnumerable<(AttributeData, IPropertySymbol)?> ExtractTargetProperties(IPropertySymbol property)
    {
        return property
            .GetAttributes()
            .Select<AttributeData, (AttributeData, IPropertySymbol)?>(attribute =>
                attribute.AttributeClass?.Name switch
                {
                    nameof(SearchableFieldAttribute) => (attribute, property),
                    _ => null
                }
            )
            .Where(it => it is not null);
    }

    private static void GenerateParameterProperty(StringBuilder propBuilder, string propertyName, string paramTypeName)
    {
        propBuilder.Append("    public ");
        propBuilder.Append(paramTypeName);
        propBuilder.Append(' ');
        propBuilder.Append(propertyName);
        propBuilder.AppendLine(" { get; init; } = new();");
    }

    protected override string GetComponentName() => "SearchParameters";
}
