name: Build and Test (Pull Request)

on:
  pull_request:
    paths:
      - src/**
      - .github/**

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build --configuration=Debug

      - name: Run Unit Tests
        run: dotnet test --filter FullyQualifiedName\!~Integration

      - name: Run Integration Tests
        run: dotnet test \
            --filter FullyQualifiedName~Integration \
            --environment AzureSearch__Endpoint="${{vars.INT_TEST_AZ_SEARCH_ENDPOINT}}" \
            --environment AzureSearch__Key="${{secrets.INT_TEST_AZ_SEARCH_KEY}}"

      - name: Determine Build Version
        id: determine_build_version
        run: |
          RUN_ID="${{ github.run_id }}"
          RUN_NO="${{ github.run_number }}"
          BUILD_VERSION="alpha$RUN_ID$RUN_NO"
          echo "version=$BUILD_VERSION" >> $GITHUB_ENV

      - name: Pack NuGet Packages
        run: |
          mkdir -p .publish
          dotnet pack \
              --output .publish \
              --no-build \
              --include-source \
              -p:SymbolPackageFormat=snupkg \
              --version-suffix="${{env.version}}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: nuget
          path: .publish/*.nupkg
          retention-days: 5
