name: Build and Release

on:
  pull_request:
    paths:
      - src/**
      - .github/**

  push:
    branches:
      - master
    paths:
      - src/**
      - .github/**

jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Pack NuGet Packages
        run: |
          mkdir -p .publish
          dotnet pack --output .publish

      - name: Publish NuGet Package
        run: |
          dotnet nuget push .publish/**.nupkg \
              --api-key {{secrets.NUGET_API_KEY}} \
              --source https://api.nuget.org/v3/index.json
